import { useEffect, useMemo, useState } from 'react';
import { operator, production, data, brands } from '../../lib/api.js';

const MODES = [
  ['ask','Ask Operator','Strategy grounded in your CCC OS data'],
  ['create','Create','Platform-native, editable content'],
  ['analyze','Analyze','Qualitative content diagnosis'],
  ['monetize','Monetize','Offers, funnels, CTAs, and orphan risks'],
  ['learn','Learn','Evidence-backed performance patterns'],
];
const FORMATS=['X post','X thread','Instagram text post','Instagram carousel outline','Instagram caption','TikTok / Reel script','YouTube idea','YouTube script','Promotional post','CTA slide','Offer-related post'];
const starter={platform:'Instagram',format:'Instagram caption',audience:'',objective:'Grow trust',length:'Medium',pillarId:'',offerId:'',ctaPreference:'',rawIdea:''};
const styles={ panel:{background:'#161616',border:'1px solid #2A2A2A',borderRadius:18,padding:18}, input:{width:'100%',background:'#0E0E0E',border:'1px solid #333',borderRadius:10,padding:'10px 12px',color:'#F5F5F5',font:'inherit'}, label:{fontSize:10,textTransform:'uppercase',letterSpacing:'.1em',color:'#777',display:'block',marginBottom:6}, button:{border:0,borderRadius:10,padding:'10px 14px',fontWeight:700,cursor:'pointer'}, muted:{color:'#8B8B8B',fontSize:12,lineHeight:1.6} };

export default function OperatorAI({activeBrand}){
  const [mode,setMode]=useState('ask'), [context,setContext]=useState(null), [prompt,setPrompt]=useState(''), [form,setForm]=useState(starter);
  const [result,setResult]=useState(null), [history,setHistory]=useState([]), [messages,setMessages]=useState([]), [conversationId,setConversationId]=useState(null);
  const [pillars,setPillars]=useState([]), [offers,setOffers]=useState([]), [loading,setLoading]=useState(false), [error,setError]=useState(''), [copied,setCopied]=useState(false), [saved,setSaved]=useState('');
  useEffect(()=>{ setResult(null);setMessages([]);setConversationId(null);setError(''); if(!activeBrand)return; Promise.all([operator.context(activeBrand.id),operator.outputs(activeBrand.id),production.ideas.list({brandId:activeBrand.id}),data.offers.list(activeBrand.id)]).then(([c,h,,o])=>{setContext(c);setHistory(h);setOffers(o)}).catch(e=>setError(e.message)); production.assets.list({brandId:activeBrand.id}).catch(()=>{}); brands.pillars.list(activeBrand.id).then(setPillars).catch(()=>setPillars([])); },[activeBrand?.id]);
  const requestText=useMemo(()=>{if(mode!=='create')return prompt; const pillar=pillars.find(x=>x.id===form.pillarId)?.name||'Not selected'; const offer=offers.find(x=>x.id===form.offerId)?.name||'Not selected'; return `Create: ${form.format}\nPlatform: ${form.platform}\nRaw idea: ${form.rawIdea}\nAudience: ${form.audience||activeBrand?.dream_customer||'Use stored brand audience if available'}\nObjective: ${form.objective}\nLength: ${form.length}\nPillar: ${pillar}\nRelevant offer: ${offer}\nCTA preference: ${form.ctaPreference||'Use judgment; do not force one'}`},[mode,prompt,form,pillars,offers,activeBrand]);
  async function run(){if(!activeBrand||!requestText.trim())return;setLoading(true);setError('');setSaved('');try{const r=await operator.run({mode,brandId:activeBrand.id,prompt:requestText,messages,conversationId});setResult(r);setConversationId(r.conversationId);setMessages(x=>[...x,{role:'user',content:requestText},{role:'assistant',content:r.content}].slice(-20));setHistory(h=>[{id:r.id,mode,title:requestText.slice(0,80),content:r.content,context_meta:r.context},...h]);}catch(e){setError(e.message)}finally{setLoading(false)}}
  async function copy(){await navigator.clipboard.writeText(result.content);setCopied(true);setTimeout(()=>setCopied(false),1400)}
  async function save(target){try{await operator.saveToProduction(result.id,target,{title:(mode==='create'?form.rawIdea:prompt).slice(0,200)||'Operator AI output',format:form.format,platform:JSON.stringify([form.platform]),pillarId:form.pillarId,content:result.content});setSaved(target)}catch(e){setError(e.message)}}
  if(!activeBrand)return <div className="page"><div style={styles.panel}>Select a brand to use Operator AI.</div></div>;
  return <div className="page" style={{maxWidth:1180,margin:'0 auto'}}>
    <div style={{marginBottom:18}}><div style={{fontSize:24,fontWeight:800}}>Operator AI</div><div style={{color:'#999',marginTop:5}}>Your AI strategist for building, growing, and monetizing theme pages.</div><div style={{marginTop:9,fontSize:11,color:'#FF6B5E'}}>Active brand: {activeBrand.name}</div></div>
    <div role="tablist" aria-label="Operator AI modes" style={{display:'flex',gap:7,overflowX:'auto',paddingBottom:8,marginBottom:12}}>{MODES.map(([id,label])=><button type="button" role="tab" aria-selected={mode===id} key={id} onClick={()=>{setMode(id);setResult(null);setError('')}} style={{...styles.button,whiteSpace:'nowrap',background:mode===id?'linear-gradient(135deg,#E8352B,#FF5449)':'#1B1B1B',color:mode===id?'#fff':'#999',border:'1px solid #2C2C2C'}}>{label}</button>)}</div>
    <div style={{display:'grid',gridTemplateColumns:'minmax(0,1fr) minmax(260px,340px)',gap:14}} className="operator-grid">
      <section style={styles.panel} aria-busy={loading}>
        <div style={{fontWeight:750,marginBottom:4}}>{MODES.find(x=>x[0]===mode)?.[1]}</div><div style={{...styles.muted,marginBottom:16}}>{MODES.find(x=>x[0]===mode)?.[2]}</div>
        {mode==='create'?<div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12}} className="operator-form-grid">
          <Field label="Platform"><select style={styles.input} value={form.platform} onChange={e=>setForm({...form,platform:e.target.value})}>{['X','Instagram','TikTok','YouTube'].map(x=><option key={x}>{x}</option>)}</select></Field>
          <Field label="Format"><select style={styles.input} value={form.format} onChange={e=>setForm({...form,format:e.target.value})}>{FORMATS.map(x=><option key={x}>{x}</option>)}</select></Field>
          <Field label="Raw idea" wide><textarea style={{...styles.input,minHeight:100,resize:'vertical'}} value={form.rawIdea} onChange={e=>setForm({...form,rawIdea:e.target.value})}/></Field>
          <Field label="Audience"><input style={styles.input} value={form.audience} onChange={e=>setForm({...form,audience:e.target.value})}/></Field><Field label="Objective"><input style={styles.input} value={form.objective} onChange={e=>setForm({...form,objective:e.target.value})}/></Field>
          <Field label="Length"><select style={styles.input} value={form.length} onChange={e=>setForm({...form,length:e.target.value})}>{['Short','Medium','Long'].map(x=><option key={x}>{x}</option>)}</select></Field>
          <Field label="Pillar"><select style={styles.input} value={form.pillarId} onChange={e=>setForm({...form,pillarId:e.target.value})}><option value="">None selected</option>{pillars.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></Field>
          <Field label="Offer"><select style={styles.input} value={form.offerId} onChange={e=>setForm({...form,offerId:e.target.value})}><option value="">None selected</option>{offers.map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select></Field>
          <Field label="CTA preference"><input style={styles.input} value={form.ctaPreference} onChange={e=>setForm({...form,ctaPreference:e.target.value})}/></Field>
        </div>:<Field label={mode==='analyze'?'Paste content to analyze':mode==='monetize'?'What should Operator diagnose or create?':mode==='learn'?'What performance question should Operator investigate?':'Ask a strategy question'}><textarea autoFocus style={{...styles.input,minHeight:150,resize:'vertical'}} maxLength={12000} value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder={mode==='ask'?'What should I post next, and why?':mode==='analyze'?'Paste the content here…':'Describe the decision you need help with…'}/></Field>}
        {error&&<div role="alert" style={{marginTop:12,color:'#FF8078',fontSize:12}}>{error}</div>}
        <button type="button" disabled={loading||!requestText.trim()} onClick={run} style={{...styles.button,marginTop:16,background:loading?'#552824':'linear-gradient(135deg,#E8352B,#FF5449)',color:'#fff',opacity:requestText.trim()?1:.7}}>{loading?'Operator is reasoning…':'Run Operator'}</button>
        {result&&<div style={{marginTop:18,borderTop:'1px solid #2A2A2A',paddingTop:18}}><textarea aria-label="Editable Operator output" value={result.content} onChange={e=>setResult({...result,content:e.target.value})} style={{...styles.input,minHeight:300,lineHeight:1.65,resize:'vertical'}}/><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:10}}><button style={{...styles.button,background:'#292929',color:'#fff'}} onClick={copy}>{copied?'Copied':'Copy'}</button><button style={{...styles.button,background:'#292929',color:'#fff'}} onClick={()=>save('idea')}>{saved==='idea'?'Saved as idea':'Save as idea'}</button><button style={{...styles.button,background:'#292929',color:'#fff'}} onClick={()=>save('asset')}>{saved==='asset'?'Saved as asset':'Save as asset'}</button><button style={{...styles.button,background:'transparent',color:'#999',border:'1px solid #333'}} onClick={()=>operator.feedback(result.id,'helpful')}>Helpful</button></div></div>}
      </section>
      <aside style={{display:'flex',flexDirection:'column',gap:12}}><div style={styles.panel}><div style={{fontWeight:700,marginBottom:10}}>Data informing Operator</div>{context?<><div style={styles.muted}>{context.evidence.length?context.evidence.join(' · '):'No connected records yet.'}</div>{context.missing.length>0&&<div style={{...styles.muted,marginTop:9,color:'#D6A74B'}}>Missing: {context.missing.join(', ')}</div>}<div style={{...styles.muted,marginTop:10}}>Stored records are evidence. Recommendations and qualitative critiques are AI judgment.</div></>:<div style={styles.muted}>Loading brand context…</div>}</div><div style={styles.panel}><div style={{fontWeight:700,marginBottom:10}}>Saved outputs</div>{history.slice(0,8).map(x=><button key={x.id} onClick={()=>setResult({id:x.id,content:x.content,context:x.context_meta})} style={{display:'block',width:'100%',textAlign:'left',background:'transparent',border:0,borderTop:'1px solid #252525',padding:'10px 0',color:'#BBB',cursor:'pointer'}}><span style={{color:'#FF6B5E',fontSize:10,textTransform:'uppercase'}}>{x.mode}</span><br/>{x.title||'Untitled output'}</button>)}{!history.length&&<div style={styles.muted}>No saved outputs yet.</div>}</div></aside>
    </div><style>{`@media(max-width:780px){.operator-grid{grid-template-columns:1fr!important}.operator-form-grid{grid-template-columns:1fr!important}.operator-wide{grid-column:auto!important}}`}</style>
  </div>
}
function Field({label,wide,children}){return <label className={wide?'operator-wide':''} style={{display:'block',gridColumn:wide?'1 / -1':'auto'}}><span style={styles.label}>{label}</span>{children}</label>}